# Generated by Django 5.2 on 2025-05-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localizacionuser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('proveedores', models.ManyToManyField(to='localizacion.proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='proveedor',
            name='repuestos',
            field=models.ManyToManyField(to='localizacion.repuesto'),
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('localizaciones', models.ManyToManyField(to='localizacion.localizacionuser')),
            ],
        ),
        migrations.AddField(
            model_name='proveedor',
            name='talleres',
            field=models.ManyToManyField(to='localizacion.taller'),
        ),
        migrations.CreateModel(
            name='Experto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('talleres', models.ManyToManyField(to='localizacion.taller')),
            ],
        ),
    ]
