# Generated by Django 5.2 on 2025-06-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizacion', '0002_rename_direccion_repuesto_modelo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taller',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
